### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by willyyang** [viestat/react-native-spotify#2]
Hey man, thanks for creating this but I don't think this works. Followed all the steps but SpotifyAuth is not in NativeModules. 

`undefined is not an object (evaluating 'SpotifyAuth.setClientID')`

Is there a step missing?

**Comment by pmilla1606** [comment]
@willyyang did you get this resolved? running into the same issue

**Comment by viestat** [comment]
@pmilla1606 In your Xcode project can you see the `SpotifyAuth.h` ,`SpotifyAuth.m`, `SpotifyLoginViewController,h` and `SpotifyLoginViewController` files in the project folder?

---

![filestructure copy](https://cloud.githubusercontent.com/assets/9158996/18105321/d48e727a-6eb3-11e6-8095-1548f3e81661.jpg)

**Comment by pmilla1606** [comment]
@viestat Yup, that did it. Thanks!

**Comment by abbasfreestyle** [comment]
Also due to the header change from 0.40 onwards the header needs to be updated from:

`#import "RCTBridgeModule.h"`

to

`#import "React/RCTBridgeModule.h"`
