### ISSUE TITLE
 [ URGENT ] No argument in the url server callback

### ISSUE THREAD

**Issue by alex3144** [viestat/react-native-spotify#22]
Hello,

To start thanks for the plugin react
 
however 
I have a problem with the connection, when I try to connect via the plugin (facebook or email) I arrive on the page below, I click on "Ok", at the level of my server I n can not retrieve the code that will allow me to build my request to recover the token.
Here are some log in the console below.

Thx

<img width="1013" alt="capture d ecran 2017-12-21 a 01 22 23" src="https://user-images.githubusercontent.com/20249485/34234885-44adad7a-e5ee-11e7-885a-96110f91c9fc.png">

**Comment by viestat** [comment]
Hello @alex3144 , 
Thanks for reporting this issue. Could you please provide a bit more context, some steps to reproduce and if possible some code snippets?

It will be much easier to help you with those :)

**Comment by alex3144** [comment]
` SpotifyModule.loggedIn((res) => {
            console.warn(res)
            if(!res) {
              SpotifyModule.startAuthenticationFlow((error) => {
                  if(!error){
                    alert("GOOD");
                  } else {
                    alert("ERRRRROOOORR", error);
                  }
                });
            }
        })`
 
in my server where i have my callback i 'am not able to find the "code" params ..........

`IN CALLBACK https://accounts.spotify.com/api/token { error: 'invalid_request',
2017-12-28T22:31:20.643+01:00 error_description: 'code must be supplied' } 400 null`
